#!/usr/bin/env python3
"""Regenerate `brain/backlog.md` from the task cards and bug files.

Reads the front matter of `brain/tasks/*/status.md` and `brain/bugs/*.md` and writes one
table per state. Idempotent; the backlog is never edited by hand (brain/README.md).
"""

from __future__ import annotations

import posixpath
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BRAIN = ROOT / "brain"
STATES = ["idea", "planned", "in_progress", "on_stand", "in_dev", "ready_for_prod", "on_prod", "closed", "parked"]
STATE_TITLES = {
    "idea": "Идеи",
    "planned": "План написан, ждёт «ок» Милы",
    "in_progress": "В работе",
    "on_stand": "На стенде",
    "in_dev": "В dev, ждёт релиза",
    "ready_for_prod": "Готово к выкатке",
    "on_prod": "На проде",
    "closed": "Закрыто",
    "parked": "Отложено",
}
ROUTES = {"feature": "фича", "micro": "микро-правка", "avaria": "авария", "content": "контент"}
REQUIRED = ("id", "slug", "title", "route", "status", "created", "updated")


def front_matter(path: Path) -> dict[str, str]:
    """Parse the simple `key: value` front matter between the first two `---` lines."""
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not match:
        return {}
    fields: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            fields[key.strip()] = value.strip()
    return fields


def validate_task(card: Path, fields: dict[str, str]) -> list[str]:
    """Problems with one task card, as human-readable strings (empty = valid)."""
    problems = [f"{card}: no front matter"] if not fields else []
    for key in REQUIRED:
        if fields and not fields.get(key):
            problems.append(f"{card}: missing `{key}`")
    if fields.get("status") and fields["status"] not in STATES:
        problems.append(f"{card}: unknown status `{fields['status']}` (expected one of {', '.join(STATES)})")
    if fields.get("route") and fields["route"] not in ROUTES:
        problems.append(f"{card}: unknown route `{fields['route']}`")
    if fields.get("id") and fields["id"] != card.parent.name.split("-", 1)[0]:
        problems.append(f"{card}: id `{fields['id']}` does not match the folder `{card.parent.name}`")
    return problems


def acceptance(card: Path) -> tuple[int, int]:
    """(done, total) checkboxes in the card."""
    text = card.read_text(encoding="utf-8")
    boxes = re.findall(r"^- \[( |x|X)\] ", text, re.M)
    return sum(1 for box in boxes if box.lower() == "x"), len(boxes)


def _page_link(task_dir: Path, folder: str, label: str, name: str) -> str:
    """A link to the plan/report page, or an honest note when the card promises a file that is not there."""
    if not name:
        return ""
    target = (task_dir / name).resolve()
    if target.exists():
        return f" · [{label}]({posixpath.normpath(posixpath.join(folder, name))})"
    return f" · {label}: обещан, файла нет"


def task_rows() -> tuple[dict[str, list[str]], list[str]]:
    rows: dict[str, list[str]] = {state: [] for state in STATES}
    problems: list[str] = []
    for card in sorted((BRAIN / "tasks").glob("*/status.md")):
        fields = front_matter(card)
        problems.extend(validate_task(card, fields))
        if not fields or fields.get("status") not in STATES:
            continue
        done, total = acceptance(card)
        folder = card.parent.relative_to(BRAIN).as_posix()
        plan = _page_link(card.parent, folder, "план", fields.get("plan", ""))
        report = _page_link(card.parent, folder, "отчёт", fields.get("report", ""))
        route = ROUTES.get(fields["route"], fields["route"])
        rows[fields["status"]].append(
            f"| {fields['id']} | [{fields['title']}]({folder}/status.md) | {route} "
            f"| `{fields.get('branch', '')}` | {done}/{total} | {fields['updated']}{plan}{report} |"
        )
    return rows, problems


def bug_rows() -> list[str]:
    rows: list[str] = []
    for bug in sorted((BRAIN / "bugs").glob("*.md")):
        fields = front_matter(bug)
        if fields.get("status", "open") == "open":
            title = fields.get("title", bug.stem)
            rows.append(f"| [{title}](bugs/{bug.name}) | {fields.get('severity', '')} | {fields.get('found', '')} |")
    return rows


def render() -> tuple[str, list[str]]:
    rows, problems = task_rows()
    lines = [
        "# Бэклог",
        "",
        f"<!-- generated by scripts/brain_index.py on {date.today().isoformat()} — do not edit by hand -->",
        "",
        "Состояния и правила — в [README.md](README.md). Карточка задачи — ссылка в первой колонке.",
        "",
    ]
    for state in STATES:
        if not rows[state]:
            continue
        lines += [
            f"## {STATE_TITLES[state]}",
            "",
            "| № | Задача | Маршрут | Ветка | Приёмка | Обновлено |",
            "|---|---|---|---|---|---|",
        ]
        lines += rows[state]
        lines.append("")
    bugs = bug_rows()
    if bugs:
        lines += ["## Открытые баги", "", "| Баг | Серьёзность | Найден |", "|---|---|---|"]
        lines += bugs
        lines.append("")
    if not any(rows.values()):
        lines += ["Задач пока нет — `/zadacha` заведёт первую.", ""]
    return "\n".join(lines), problems


def main() -> int:
    text, problems = render()
    (BRAIN / "backlog.md").write_text(text, encoding="utf-8")
    for problem in problems:
        print(problem, file=sys.stderr)
    print(f"brain/backlog.md regenerated ({len(list((BRAIN / 'tasks').glob('*/status.md')))} task cards)")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
