"""initial schema

Revision ID: 793d0a764d28
Revises:
Create Date: 2026-09-03 19:37:23.823292

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "793d0a764d28"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `btree_gist` is required by the EXCLUDE constraint that keeps weeks from overlapping.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_actor_id"), "audit_log", ["actor_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("status", sa.String(length=16), server_default="queued", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name=op.f("ck_jobs_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index("ix_jobs_status_run_after", "jobs", ["status", "run_after"], unique=False)
    op.create_table(
        "reminder_log",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("recipients", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_reminder_log")),
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("title_accusative", sa.String(length=255), server_default="", nullable=False),
        sa.Column("hashtag", sa.String(length=64), server_default="", nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("daily_kind", sa.String(length=16), nullable=True),
        sa.Column("daily_title", sa.Text(), server_default="", nullable=False),
        sa.Column("daily_note", sa.Text(), server_default="", nullable=False),
        sa.Column("base_freezes", sa.Integer(), server_default=sa.text("2"), nullable=False),
        sa.Column("max_freezes", sa.Integer(), server_default=sa.text("5"), nullable=False),
        sa.Column("level_tourist", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("level_traveler", sa.Integer(), server_default=sa.text("4"), nullable=False),
        sa.Column("level_resident", sa.Integer(), server_default=sa.text("9"), nullable=False),
        sa.Column("journal_promise_on", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("daily_kind IS NULL OR daily_kind IN ('tzolkin')", name=op.f("ck_seasons_daily_kind")),
        sa.CheckConstraint("status IN ('draft', 'active', 'archived')", name=op.f("ck_seasons_status")),
        sa.CheckConstraint("ends_on >= starts_on", name=op.f("ck_seasons_dates")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint("slug", name="uq_seasons_slug"),
    )
    op.create_index(
        "uq_seasons_single_active", "seasons", ["status"], unique=True, postgresql_where=sa.text("status = 'active'")
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "achievement_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("emoji", sa.String(length=16), server_default="", nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("sort", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], name=op.f("fk_achievement_types_season_id_seasons")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievement_types")),
        sa.UniqueConstraint("season_id", "code", name="uq_achievement_types_season_id_code"),
    )
    op.create_index(op.f("ix_achievement_types_season_id"), "achievement_types", ["season_id"], unique=False)
    op.create_table(
        "achievements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), server_default="", nullable=False),
        sa.Column("awarded_by", sa.BigInteger(), nullable=True),
        sa.Column("awarded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["awarded_by"], ["users.id"], name=op.f("fk_achievements_awarded_by_users")),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], name=op.f("fk_achievements_season_id_seasons")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_achievements_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievements")),
        sa.UniqueConstraint("season_id", "user_id", "code", name="uq_achievements_season_id_user_id_code"),
    )
    op.create_index(op.f("ix_achievements_season_id"), "achievements", ["season_id"], unique=False)
    op.create_index(op.f("ix_achievements_user_id"), "achievements", ["user_id"], unique=False)
    op.create_table(
        "dialog_states",
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_dialog_states_user_id_users")),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_dialog_states")),
    )
    op.create_table(
        "freezes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=16), nullable=False),
        sa.Column("granted_by", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "reason IN ('word', 'max', 'comment', 'meetup', 'friend', 'manual')", name=op.f("ck_freezes_reason")
        ),
        sa.ForeignKeyConstraint(["granted_by"], ["users.id"], name=op.f("fk_freezes_granted_by_users")),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], name=op.f("fk_freezes_season_id_seasons")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_freezes_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_freezes")),
    )
    op.create_index(op.f("ix_freezes_season_id"), "freezes", ["season_id"], unique=False)
    op.create_index(op.f("ix_freezes_user_id"), "freezes", ["user_id"], unique=False)
    op.create_table(
        "season_members",
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], name=op.f("fk_season_members_season_id_seasons")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_season_members_user_id_users")),
        sa.PrimaryKeyConstraint("season_id", "user_id", name="pk_season_members"),
    )
    op.create_table(
        "weeks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("intro", sa.Text(), server_default="", nullable=False),
        sa.Column("task_min", sa.Text(), server_default="", nullable=False),
        sa.Column("task_max", sa.Text(), server_default="", nullable=False),
        sa.Column("word", sa.String(length=255), server_default="", nullable=False),
        sa.Column("word_ru", sa.String(length=255), server_default="", nullable=False),
        sa.Column("word_meaning", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("ends_on >= starts_on", name=op.f("ck_weeks_dates")),
        sa.CheckConstraint("number >= 1", name=op.f("ck_weeks_number")),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], name=op.f("fk_weeks_season_id_seasons")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weeks")),
        sa.UniqueConstraint("season_id", "number", name="uq_weeks_season_id_number"),
        sa.UniqueConstraint("season_id", "id", name="uq_weeks_season_id_id"),
    )
    op.create_index(op.f("ix_weeks_season_id"), "weeks", ["season_id"], unique=False)
    op.execute(
        "ALTER TABLE weeks ADD CONSTRAINT weeks_no_overlap "
        "EXCLUDE USING gist (season_id WITH =, daterange(starts_on, ends_on, '[]') WITH &&) "
        "DEFERRABLE INITIALLY IMMEDIATE"
    )
    op.create_table(
        "wishes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], name=op.f("fk_wishes_season_id_seasons")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_wishes_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wishes")),
        sa.UniqueConstraint("season_id", "user_id", name="uq_wishes_season_id_user_id"),
    )
    op.create_index(op.f("ix_wishes_season_id"), "wishes", ["season_id"], unique=False)
    op.create_index(op.f("ix_wishes_user_id"), "wishes", ["user_id"], unique=False)
    op.create_table(
        "facts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("week_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_facts_author_id_users")),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], name=op.f("fk_facts_season_id_seasons")),
        sa.ForeignKeyConstraint(
            ["season_id", "week_id"],
            ["weeks.season_id", "weeks.id"],
            name="fk_facts_season_id_week_id_weeks",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facts")),
    )
    op.create_index(op.f("ix_facts_author_id"), "facts", ["author_id"], unique=False)
    op.create_index(op.f("ix_facts_season_id"), "facts", ["season_id"], unique=False)
    op.create_index(op.f("ix_facts_week_id"), "facts", ["week_id"], unique=False)
    op.create_table(
        "intents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("week_id", sa.Integer(), nullable=False),
        sa.Column("choice", sa.String(length=16), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("choice IN ('take', 'try', 'skip')", name=op.f("ck_intents_choice")),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], name=op.f("fk_intents_season_id_seasons")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_intents_user_id_users")),
        sa.ForeignKeyConstraint(
            ["season_id", "week_id"],
            ["weeks.season_id", "weeks.id"],
            name="fk_intents_season_id_week_id_weeks",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intents")),
        sa.UniqueConstraint("user_id", "week_id", name="uq_intents_user_id_week_id"),
    )
    op.create_index(op.f("ix_intents_season_id"), "intents", ["season_id"], unique=False)
    op.create_index(op.f("ix_intents_user_id"), "intents", ["user_id"], unique=False)
    op.create_index(op.f("ix_intents_week_id"), "intents", ["week_id"], unique=False)
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("week_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("tg_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("tg_message_id", sa.BigInteger(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('text', 'photo', 'video', 'video_note', 'document', 'voice', 'audio', 'other')",
            name=op.f("ck_reports_kind"),
        ),
        sa.CheckConstraint("level IN ('min', 'max')", name=op.f("ck_reports_level")),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], name=op.f("fk_reports_season_id_seasons")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_reports_user_id_users")),
        sa.ForeignKeyConstraint(
            ["season_id", "week_id"],
            ["weeks.season_id", "weeks.id"],
            name="fk_reports_season_id_week_id_weeks",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_season_id"), "reports", ["season_id"], unique=False)
    op.create_index(op.f("ix_reports_user_id"), "reports", ["user_id"], unique=False)
    op.create_index(op.f("ix_reports_week_id"), "reports", ["week_id"], unique=False)
    op.create_table(
        "stamps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("week_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("week_title_snapshot", sa.String(length=255), server_default="", nullable=False),
        sa.Column("awarded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("source", sa.String(length=16), server_default="report", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("level IN ('min', 'max')", name=op.f("ck_stamps_level")),
        sa.CheckConstraint("source IN ('report', 'admin')", name=op.f("ck_stamps_source")),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], name=op.f("fk_stamps_season_id_seasons")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_stamps_user_id_users")),
        sa.ForeignKeyConstraint(
            ["season_id", "week_id"],
            ["weeks.season_id", "weeks.id"],
            name="fk_stamps_season_id_week_id_weeks",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stamps")),
        sa.UniqueConstraint("user_id", "week_id", name="uq_stamps_user_id_week_id"),
    )
    op.create_index(op.f("ix_stamps_season_id"), "stamps", ["season_id"], unique=False)
    op.create_index(op.f("ix_stamps_user_id"), "stamps", ["user_id"], unique=False)
    op.create_index(op.f("ix_stamps_week_id"), "stamps", ["week_id"], unique=False)
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("week_id", sa.Integer(), nullable=True),
        sa.Column("word", sa.String(length=255), nullable=False),
        sa.Column("meaning", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], name=op.f("fk_words_season_id_seasons")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_words_user_id_users")),
        sa.ForeignKeyConstraint(
            ["season_id", "week_id"],
            ["weeks.season_id", "weeks.id"],
            name="fk_words_season_id_week_id_weeks",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_words")),
    )
    op.create_index(op.f("ix_words_season_id"), "words", ["season_id"], unique=False)
    op.create_index(op.f("ix_words_user_id"), "words", ["user_id"], unique=False)
    op.create_index(op.f("ix_words_week_id"), "words", ["week_id"], unique=False)
    op.create_table(
        "admin_links",
        sa.Column("admin_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("admin_message_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=True),
        sa.Column("week_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], name=op.f("fk_admin_links_report_id_reports")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_admin_links_user_id_users")),
        sa.ForeignKeyConstraint(["week_id"], ["weeks.id"], name=op.f("fk_admin_links_week_id_weeks")),
        sa.PrimaryKeyConstraint("admin_chat_id", "admin_message_id", name="pk_admin_links"),
    )
    op.create_index(op.f("ix_admin_links_user_id"), "admin_links", ["user_id"], unique=False)
    op.create_table(
        "media",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("tg_file_id", sa.Text(), nullable=False),
        sa.Column("tg_file_unique_id", sa.String(length=255), nullable=True),
        sa.Column("mime", sa.String(length=255), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], name=op.f("fk_media_report_id_reports")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media")),
    )
    op.create_index(op.f("ix_media_report_id"), "media", ["report_id"], unique=False)
    op.create_index(op.f("ix_media_sha256"), "media", ["sha256"], unique=False)
    op.create_index(op.f("ix_media_tg_file_unique_id"), "media", ["tg_file_unique_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_tg_file_unique_id"), table_name="media")
    op.drop_index(op.f("ix_media_sha256"), table_name="media")
    op.drop_index(op.f("ix_media_report_id"), table_name="media")
    op.drop_table("media")
    op.drop_index(op.f("ix_admin_links_user_id"), table_name="admin_links")
    op.drop_table("admin_links")
    op.drop_index(op.f("ix_words_week_id"), table_name="words")
    op.drop_index(op.f("ix_words_user_id"), table_name="words")
    op.drop_index(op.f("ix_words_season_id"), table_name="words")
    op.drop_table("words")
    op.drop_index(op.f("ix_stamps_week_id"), table_name="stamps")
    op.drop_index(op.f("ix_stamps_user_id"), table_name="stamps")
    op.drop_index(op.f("ix_stamps_season_id"), table_name="stamps")
    op.drop_table("stamps")
    op.drop_index(op.f("ix_reports_week_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_user_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_season_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_intents_week_id"), table_name="intents")
    op.drop_index(op.f("ix_intents_user_id"), table_name="intents")
    op.drop_index(op.f("ix_intents_season_id"), table_name="intents")
    op.drop_table("intents")
    op.drop_index(op.f("ix_facts_week_id"), table_name="facts")
    op.drop_index(op.f("ix_facts_season_id"), table_name="facts")
    op.drop_index(op.f("ix_facts_author_id"), table_name="facts")
    op.drop_table("facts")
    op.drop_index(op.f("ix_wishes_user_id"), table_name="wishes")
    op.drop_index(op.f("ix_wishes_season_id"), table_name="wishes")
    op.drop_table("wishes")
    op.drop_index(op.f("ix_weeks_season_id"), table_name="weeks")
    op.drop_table("weeks")
    op.drop_table("season_members")
    op.drop_index(op.f("ix_freezes_user_id"), table_name="freezes")
    op.drop_index(op.f("ix_freezes_season_id"), table_name="freezes")
    op.drop_table("freezes")
    op.drop_table("dialog_states")
    op.drop_index(op.f("ix_achievements_user_id"), table_name="achievements")
    op.drop_index(op.f("ix_achievements_season_id"), table_name="achievements")
    op.drop_table("achievements")
    op.drop_index(op.f("ix_achievement_types_season_id"), table_name="achievement_types")
    op.drop_table("achievement_types")
    op.drop_table("users")
    op.drop_table("settings")
    op.drop_index("uq_seasons_single_active", table_name="seasons", postgresql_where=sa.text("status = 'active'"))
    op.drop_table("seasons")
    op.drop_table("reminder_log")
    op.drop_index("ix_jobs_status_run_after", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_audit_log_actor_id"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS btree_gist")
